56347name = "ya-hyde-hyde"
license = "MIT"
licenselink = "https://github.com/tanzy/ya-hyde-hyde/blob/main/LICENSE.md"
description = "A simply cool Hyde inspired theme, based of hyde-hyde from https://github.com/htr3n/hyde-hyde"
tags = ["blog", "theme", "hyde", "highlight.js", "font-awesome", "google analytics", "disqus", "personal", "syntax highlighting", "responsive", "graphcomment"]
features = ["blog", "theme", "highlight.js", "font-awesome", "responsive", "disqus", "graphcomment", "portfolio"]
homepage = "https://github.com/tanzy/ya-hyde-hyde"
min_version = "0.43"

[author]
    name = "tanzy"
    homepage = "https://tanzy.github.io"

# If Porting existing theme
[original]
    author =  "htr3n"
    homepage = "https://htr3n.github.io"
    repo = "https://github.com/htr3n/hyde-hyde"
